version: '3.9'

services:
  bot_benevole:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISCORD_TOKEN: "YOU_BOT_TOKEN_HERE"
    volumes:
      - ./planning.json:/app/planning.json
      - ./cron.txt:/app/cron.txt
    restart: unless-stopped
