version: "3.9"

services:
  vogonplan:
    image: ghcr.io/nimon77/vogonplan:latest
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      ENGINE_URL: ${ENGINE_URL}
      # DEBUG: "true"
    restart: unless-stopped
  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_USER: vogon

volumes:
  postgres_data:
